name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install autoconf automake  # إذا كنت تستخدم Autotools
      - name: Generate configure
        run: autoreconf -i
      - name: Run configure
        run: ./configure
      - name: Build
        run: make
